name: Monorepo CI/CD

on:
  workflow_dispatch: 
  
  push:
    branches: [ main, master ] 
    paths:
      - 'services/**'
      - 'charts/**'
      - '.github/workflows/**'

env:
  REGISTRY: ghcr.io
  repo_owner: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [go-app, node-app]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # Required to check changes

    - name: Check for changes
      id: check_changes
      run: |
        # ALWAYS build if triggered manually
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "Manual trigger detected: Forcing build."
          echo "changed=true" >> $GITHUB_OUTPUT
        
        # Otherwise, check Git history for changes
        elif git diff --name-only HEAD^ HEAD | grep "services/${{ matrix.service }}/"; then
          echo "Changes detected in ${{ matrix.service }}."
          echo "changed=true" >> $GITHUB_OUTPUT
          
        else
          echo "No changes in ${{ matrix.service }}."
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Log in to the Container registry
      if: steps.check_changes.outputs.changed == 'true'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      if: steps.check_changes.outputs.changed == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./services/${{ matrix.service }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.repo_owner }}/${{ matrix.service }}:latest,${{ env.REGISTRY }}/${{ env.repo_owner }}/${{ matrix.service }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1

    - name: Deploy Go App (Dry Run)
      run: |
        helm upgrade --install go-app ./charts/microservice \
          --set image.repository=${{ env.REGISTRY }}/${{ env.repo_owner }}/go-app \
          --set image.tag=${{ github.sha }} \
          --set service.targetPort=8080 \
          --dry-run

    - name: Deploy Node App (Dry Run)
      run: |
        helm upgrade --install node-app ./charts/microservice \
          --set image.repository=${{ env.REGISTRY }}/${{ env.repo_owner }}/node-app \
          --set image.tag=${{ github.sha }} \
          --set service.targetPort=3000 \
          --dry-run